# Generated by Django 4.0.4 on 2022-04-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_title_alter_listing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='officaial_homepage',
            new_name='official_homepage',
        ),
    ]
